import tensorflow_decision_forests as tfdf

features=[
    #tfdf.keras.FeatureUsage('src_ip', tfdf.keras.FeatureSemantic.NUMERICAL),
    #tfdf.keras.FeatureUsage('dst_ip' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('src_port' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('dst_port' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('protocol' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('pkt_length' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('info' , tfdf.keras.FeatureSemantic.NUMERICAL),
    #tfdf.keras.FeatureUsage('timestamp' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('flow_duration' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('flow_byts_s' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('flow_pkts_s' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_pkts_s' , tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_pkts_s', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('tot_fwd_pkts', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('tot_bwd_pkts', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('totlen_fwd_pkts', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('totlen_bwd_pkts', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_pkt_len_max', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_pkt_len_min', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_pkt_len_mean', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_pkt_len_std', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_pkt_len_max', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_pkt_len_min', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_pkt_len_mean', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_pkt_len_std', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('pkt_len_max', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('pkt_len_min', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('pkt_len_mean', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('pkt_len_std', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('pkt_len_var', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_header_len', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_header_len', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_seg_size_min', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_act_data_pkts', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('flow_iat_mean', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('flow_iat_max', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('flow_iat_min', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('flow_iat_std', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_iat_tot', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_iat_max', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_iat_min', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_iat_mean', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_iat_std', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_iat_tot', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_iat_max', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_iat_min', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_iat_mean', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_iat_std', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_psh_flags', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_psh_flags', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_urg_flags', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_urg_flags', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fin_flag_cnt', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('syn_flag_cnt', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('rst_flag_cnt', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('psh_flag_cnt', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('ack_flag_cnt', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('urg_flag_cnt', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('ece_flag_cnt', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('down_up_ratio', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('pkt_size_avg', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('init_fwd_win_byts', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('init_bwd_win_byts', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('active_max', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('active_min', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('active_mean', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('active_std', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('idle_max', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage( 'idle_min', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('idle_mean', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('idle_std', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_byts_b_avg', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_pkts_b_avg', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_byts_b_avg', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_pkts_b_avg', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('fwd_blk_rate_avg', tfdf.keras.FeatureSemantic.NUMERICAL),
    tfdf.keras.FeatureUsage('bwd_blk_rate_avg', tfdf.keras.FeatureSemantic.NUMERICAL),
    #tfdf.keras.FeatureUsage('Target', tfdf.keras.FeatureSemantic.NUMERICAL)
]
